export const mockAgents = [
  {
    id: "agent-1",
    name: "Support Bot",
    status: "online" as const,
    model: "claude-sonnet-4-20250514",
    channel: "Telegram",
    lastActive: "2 min ago",
    sessions: 142,
    tokensUsed: 1_240_000,
    costEstimate: 4.82,
    memoryFiles: 3,
  },
  {
    id: "agent-2",
    name: "Sales Assistant",
    status: "idle" as const,
    model: "gpt-4o",
    channel: "Discord",
    lastActive: "15 min ago",
    sessions: 87,
    tokensUsed: 890_000,
    costEstimate: 3.21,
    memoryFiles: 2,
  },
  {
    id: "agent-3",
    name: "Code Reviewer",
    status: "online" as const,
    model: "claude-sonnet-4-20250514",
    channel: "Slack",
    lastActive: "Just now",
    sessions: 234,
    tokensUsed: 2_100_000,
    costEstimate: 8.14,
    memoryFiles: 5,
  },
  {
    id: "agent-4",
    name: "Research Agent",
    status: "error" as const,
    model: "gemini-2.0-flash",
    channel: "WhatsApp",
    lastActive: "1 hr ago",
    sessions: 56,
    tokensUsed: 430_000,
    costEstimate: 1.12,
    memoryFiles: 1,
  },
];

export const mockSessions = [
  {
    id: "sess-1",
    agentName: "Support Bot",
    user: "alice@example.com",
    started: "2024-01-15 14:30",
    messages: 24,
    tokens: 12_400,
    status: "active" as const,
    preview: "How do I reset my password? I've tried the forgot password link but...",
  },
  {
    id: "sess-2",
    agentName: "Code Reviewer",
    user: "bob@team.dev",
    started: "2024-01-15 14:15",
    messages: 8,
    tokens: 45_200,
    status: "active" as const,
    preview: "Review PR #342: Refactor authentication middleware to use JWT...",
  },
  {
    id: "sess-3",
    agentName: "Sales Assistant",
    user: "carol@prospect.io",
    started: "2024-01-15 13:45",
    messages: 16,
    tokens: 8_900,
    status: "ended" as const,
    preview: "What's the difference between your Pro and Enterprise plans?",
  },
  {
    id: "sess-4",
    agentName: "Support Bot",
    user: "dave@example.com",
    started: "2024-01-15 13:20",
    messages: 6,
    tokens: 3_200,
    status: "ended" as const,
    preview: "I need to update my billing information. Can you help me with...",
  },
  {
    id: "sess-5",
    agentName: "Research Agent",
    user: "eve@lab.org",
    started: "2024-01-15 12:00",
    messages: 32,
    tokens: 67_800,
    status: "error" as const,
    preview: "Analyze the latest papers on transformer architectures from...",
  },
];

export const mockCronJobs = [
  {
    id: "cron-1",
    name: "Memory Consolidation",
    schedule: "0 */6 * * *",
    description: "Consolidate daily memory files into weekly summaries",
    lastRun: "2024-01-15 12:00",
    nextRun: "2024-01-15 18:00",
    status: "success" as const,
    agent: "Support Bot",
  },
  {
    id: "cron-2",
    name: "Channel Health Check",
    schedule: "*/15 * * * *",
    description: "Ping all connected channels to verify connectivity",
    lastRun: "2024-01-15 14:30",
    nextRun: "2024-01-15 14:45",
    status: "success" as const,
    agent: "System",
  },
  {
    id: "cron-3",
    name: "Daily Report",
    schedule: "0 9 * * *",
    description: "Generate daily activity report and send to admin channel",
    lastRun: "2024-01-15 09:00",
    nextRun: "2024-01-16 09:00",
    status: "success" as const,
    agent: "Support Bot",
  },
  {
    id: "cron-4",
    name: "Token Usage Alert",
    schedule: "0 * * * *",
    description: "Check token usage and alert if approaching limits",
    lastRun: "2024-01-15 14:00",
    nextRun: "2024-01-15 15:00",
    status: "warning" as const,
    agent: "System",
  },
  {
    id: "cron-5",
    name: "Stale Session Cleanup",
    schedule: "0 3 * * *",
    description: "Remove sessions inactive for more than 24 hours",
    lastRun: "2024-01-15 03:00",
    nextRun: "2024-01-16 03:00",
    status: "failed" as const,
    agent: "System",
  },
];

export const mockSkills = [
  {
    id: "skill-1",
    name: "web-search",
    description: "Search the web using Google/Bing APIs and return summarized results",
    version: "1.2.0",
    enabled: true,
    agents: ["Support Bot", "Research Agent"],
    source: "clawhub",
  },
  {
    id: "skill-2",
    name: "code-interpreter",
    description: "Execute Python code in a sandboxed environment and return results",
    version: "2.0.1",
    enabled: true,
    agents: ["Code Reviewer"],
    source: "clawhub",
  },
  {
    id: "skill-3",
    name: "calendar-sync",
    description: "Read and create Google Calendar events for scheduling",
    version: "0.9.3",
    enabled: true,
    agents: ["Sales Assistant"],
    source: "clawhub",
  },
  {
    id: "skill-4",
    name: "image-gen",
    description: "Generate images using DALL-E or Stable Diffusion APIs",
    version: "1.0.0",
    enabled: false,
    agents: [],
    source: "clawhub",
  },
  {
    id: "skill-5",
    name: "pdf-reader",
    description: "Extract and analyze text content from PDF documents",
    version: "1.1.2",
    enabled: true,
    agents: ["Research Agent", "Support Bot"],
    source: "local",
  },
  {
    id: "skill-6",
    name: "email-sender",
    description: "Send emails via SMTP or SendGrid with templating support",
    version: "0.8.0",
    enabled: false,
    agents: [],
    source: "clawhub",
  },
  {
    id: "skill-7",
    name: "db-query",
    description: "Execute read-only SQL queries against configured databases",
    version: "1.3.0",
    enabled: true,
    agents: ["Support Bot"],
    source: "local",
  },
  {
    id: "skill-8",
    name: "github-ops",
    description: "Create issues, review PRs, and manage GitHub repositories",
    version: "2.1.0",
    enabled: true,
    agents: ["Code Reviewer"],
    source: "clawhub",
  },
];

export const mockMemoryFiles = [
  {
    path: "agents/support-bot/MEMORY.md",
    agent: "Support Bot",
    size: "4.2 KB",
    modified: "2024-01-15 14:20",
    preview: "# Support Bot Memory\n\n## User Preferences\n- alice@example.com prefers concise answers\n- dave@example.com needs step-by-step instructions\n\n## Common Issues\n- Password reset: Direct to /settings/security\n- Billing: Direct to /billing/update\n- API keys: Check rate limit first\n\n## Learned Patterns\n- Most support queries peak between 9-11 AM PST\n- 40% of queries are about password resets\n- Users from enterprise plans expect faster responses",
  },
  {
    path: "agents/support-bot/2024-01-15.md",
    agent: "Support Bot",
    size: "1.8 KB",
    modified: "2024-01-15 14:30",
    preview: "# Daily Log - Jan 15, 2024\n\n## Sessions: 12\n## Resolved: 10\n## Escalated: 2\n\n### Notable\n- alice@example.com had recurring password issue - flagged for engineering\n- New user onboarding flow confused 3 users today",
  },
  {
    path: "agents/code-reviewer/MEMORY.md",
    agent: "Code Reviewer",
    size: "6.1 KB",
    modified: "2024-01-15 14:25",
    preview: "# Code Reviewer Memory\n\n## Team Standards\n- Use TypeScript strict mode\n- All PRs need at least 1 approval\n- No console.log in production code\n\n## Common Issues\n- Missing error handling in async functions\n- Inconsistent naming conventions in /api routes\n- Unused imports not cleaned up",
  },
  {
    path: "agents/sales-assistant/MEMORY.md",
    agent: "Sales Assistant",
    size: "2.9 KB",
    modified: "2024-01-15 13:45",
    preview: "# Sales Assistant Memory\n\n## Pricing Tiers\n- Starter: $29/mo\n- Pro: $79/mo\n- Enterprise: Custom\n\n## Competitor Intel\n- Competitor A launched new feature last week\n- Our advantage: Better API integration\n\n## Hot Leads\n- carol@prospect.io - Enterprise interest, follow up Friday",
  },
  {
    path: "agents/research-agent/MEMORY.md",
    agent: "Research Agent",
    size: "8.4 KB",
    modified: "2024-01-15 12:00",
    preview: "# Research Agent Memory\n\n## Active Research Topics\n- Transformer architecture improvements\n- RAG optimization techniques\n- Multi-agent coordination patterns\n\n## Sources Database\n- arxiv.org: Primary for ML papers\n- semantic scholar: Citation tracking\n- GitHub trending: Implementation references",
  },
];

export const mockHealthCheck = {
  gateway: {
    status: "running" as const,
    uptime: 172800,
    version: "0.9.4",
    pid: 42851,
    memory: "124 MB",
  },
  channels: [
    { name: "Telegram", status: "connected" as const, latency: "45ms", lastPing: "2s ago" },
    { name: "Discord", status: "connected" as const, latency: "62ms", lastPing: "3s ago" },
    { name: "Slack", status: "connected" as const, latency: "38ms", lastPing: "1s ago" },
    { name: "WhatsApp", status: "error" as const, latency: "—", lastPing: "5 min ago", error: "Auth token expired" },
  ],
  models: [
    { provider: "Anthropic", model: "claude-sonnet-4-20250514", status: "reachable" as const, latency: "210ms" },
    { provider: "OpenAI", model: "gpt-4o", status: "reachable" as const, latency: "185ms" },
    { provider: "Google", model: "gemini-2.0-flash", status: "unreachable" as const, latency: "—", error: "API key invalid" },
  ],
  errors: [
    { time: "14:32:01", level: "error" as const, message: "WhatsApp channel disconnected: Auth token expired", source: "channel-manager" },
    { time: "14:30:15", level: "warning" as const, message: "Token usage at 80% of daily limit for agent 'Research Agent'", source: "rate-limiter" },
    { time: "14:28:44", level: "error" as const, message: "Failed to reach Gemini API: Invalid API key", source: "model-proxy" },
    { time: "14:15:02", level: "warning" as const, message: "Session sess-5 timed out after 30 minutes of inactivity", source: "session-manager" },
    { time: "13:58:30", level: "info" as const, message: "Agent 'Sales Assistant' entered idle state", source: "agent-manager" },
    { time: "13:45:12", level: "warning" as const, message: "Memory file approaching size limit (8.4 KB / 10 KB) for Research Agent", source: "memory-manager" },
    { time: "13:30:00", level: "info" as const, message: "Cron job 'Channel Health Check' completed successfully", source: "cron-scheduler" },
    { time: "13:15:22", level: "error" as const, message: "Stale session cleanup failed: Permission denied on /tmp/sessions", source: "cron-scheduler" },
  ],
};
